import { MainView } from "mainView.slint";
import { Library } from "library.slint";
import { Queue } from "queue.slint";
import { Player } from "player.slint";
import "../fonts/Ubuntu/UbuntuNerdFont-Regular.ttf";
import "../fonts/Ubuntu/UbuntuNerdFont-Bold.ttf";

export component MainWindow inherits Window {
	title: "Slash";
	default-font-family: "Ubuntu Nerd Font";
	background: #0F0F0F;

	VerticalLayout {
		HorizontalLayout {
			Library {}
			MainView {}
			Queue {}
		}
		Player {height: 96px;}
	}
}
