import "../fonts/Ubuntu/UbuntuNerdFont-Regular.ttf";
import "../fonts/Ubuntu/UbuntuNerdFont-Bold.ttf";
import { VerticalBox, Button, LineEdit, ListView } from "std-widgets.slint";
import { Library } from "library.slint";
import { Queue } from "queue.slint";
import { Player } from "player.slint";

export global Logic {
	in property <[string]> mainViewData;
	in-out property <string> searchText;
	callback search();
}

component MainView {
	in property ViewData <=> Logic.mainViewData;
	out property searchText <=> Logic.searchText;

	callback search <=> Logic.search;

	VerticalBox {
		HorizontalLayout {
			spacing: 8px;
			Button { text: ""; }
			Button { text: ""; }
			searchBar := LineEdit {
				height: 32px;
				placeholder-text: "Search";
				edited => { searchText = self.text; search() }
			}
		}
		list := ListView {
			for data in ViewData : Rectangle {
				height: 32px;
				Text {
					text: data;
				}
			}
		}
	}
}

export component MainWindow inherits Window {
	title: "Slash";
	default-font-family: "Ubuntu Nerd Font";
	background: #0F0F0F;

	VerticalLayout {
		HorizontalLayout {
			Library {}
			MainView {}
			Queue {}
		}
		Player {height: 96px;}
	}
}
