import { TextEdit , LineEdit, ScrollView, Button, HorizontalBox, VerticalBox, TabWidget, TabBarImpl} from "std-widgets.slint";
export component MainView {
	preferred-height: 100%;
	preferred-width: 100%;

	VerticalBox {
		HorizontalLayout {
			spacing: 8px;
			Button { text: "<"; }
			Button { text: ">"; }
			LineEdit {
				height: 32px;
				placeholder-text: "Search";
			}
		}
		Text {
			font-size: 96px;
			font-weight: 700;
			text: "Main View";
			vertical-alignment: center;
			horizontal-alignment: center;
		}
	}
}