import { Button , ScrollView, VerticalBox} from "std-widgets.slint";

export component Queue {
	width: 58px;
	animate width { duration: 128ms; easing: ease-in-out; }
	
	HorizontalLayout {
		alignment: end;
		Rectangle {
			width: 50%;
			background: #282828;
		}
	}
	Rectangle { background: #282828; border-radius: 8px;}

	VerticalBox {
		padding-right: 8px;
		HorizontalLayout {
			height: 32px;
			ToggleBar := Button {
				text: "";
				width: 40px;
				clicked => {
					if (self.text == "") {
						self.text = "";
						root.width = 256px;
					}
					else {
						self.text = "";
						root.width = 58px;
					}
				}
			}
			Text {
				font-size: 27px;
				font-weight: 700;
				horizontal-alignment: right;
				vertical-alignment: center;
				text: ToggleBar.text == "" ? "Queue" : "";
			}
		}
		Text {
			font-size: 22px;
			font-weight: 700;
			height: 32px;
			text: ToggleBar.text == "" ? "Currently Playing" : "";
		}
		Text {
			font-size: 22px;
			font-weight: 700;
			height: 32px;
			text: ToggleBar.text == "" ? "Next Up" : "";
		}
		ScrollView {}
	}
}